### PR TITLE
use correct pkg-config name for libsodium

### PR DESCRIPTION
**Pull request by plicease**
This allows using this system libsodium if it is available.

### CODE REVIEW

**Comment by plicease** [comment]
Btw- if a specific version of libsodium is required we can add a check for that.

**Comment by ajgb** [comment]
Thanks for your patch and Alien::Base in general!

**Comment by plicease** [comment]
@ajgb make sure you have the most recent [Alien] when you roll a new release, as older versions do not support isloate_dynamic.

Thanks!

**Comment by ajgb** [comment]
@plicease I must admit, that I'm a bit lost in the list of available options provided by `Alien::Base` - from the quick look it seems that I'd need to override the `alien_check_installed_version` to ensure that the correct version of library is used, is that correct?

**Comment by plicease** [comment]
@ajgb, you don't need `alien_check_installed_version` in this case because libsodium comes with a .pc (pkg-config) file.

**Comment by plicease** [comment]
Give me a sec.  I misunderstood what you were asking.

**Pull request merged**
